name:                killer-slackbot
version:             0.1.0.0
github:              "benjaminaltieri/killer-slackbot"
license:             BSD3
author:              "Ben Altieri"
maintainer:          "benaltieri@gmail.com"
copyright:           "2018 Benjamin Altieri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            simply a killer slackbot
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/killer-slackbot#readme>

dependencies:
- base >= 4.7 && < 5
- dotenv
- wreq
- text
- lens
- bytestring
- aeson
- lens-aeson
- wuss
- websockets
- network-uri

library:
  source-dirs: src

executables:
  killer-slackbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - killer-slackbot

tests:
  killer-slackbot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - killer-slackbot
